meta_product_name: “Code Labs”

meta_title: "Code Labs: Code School With AI"

meta_description: "Master Code with Industry-Led Courses. Code smarter with AI—your virtual mentor for instant feedback. Elevate your skills with real-time, personalized guidance. Unleash your coding excellence!"

meta_image: "codelabs_logo.png" # should exist in `app/assets/images/`
