development:
  secret_key_base: key
  publishable_key: pk_test_51OJfuEA7UmY4VSRu46WukT08pC8Qv5iOEhCK9nGgbUTq5IjKDG0Ijb1JAL4CKyoNHAsN78wDcmhg8QH4gWYyFYKk003xpQbJcU
  secret_key: sk_test_51OJfuEA7UmY4VSRugNYy7hQOx2VQV5eyzxE91E3gd2rL6E8bDU0QUOADSvcE6htp6Eev1ZGJvSmTV4Mjkal8wOiJ00xOo59e4z
